[package]
name = "libtest2"
version = "0.0.3"
description = "An experimental replacement for libtest"
categories = ["development-tools::testing"]
keywords = ["libtest"]
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
include.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs", "--generate-link-to-definition"]

[package.metadata.release]
pre-release-replacements = [
  {file="CHANGELOG.md", search="Unreleased", replace="{{version}}", min=1},
  {file="CHANGELOG.md", search="\\.\\.\\.HEAD", replace="...{{tag_name}}", exactly=1},
  {file="CHANGELOG.md", search="ReleaseDate", replace="{{date}}", min=1},
  {file="CHANGELOG.md", search="<!-- next-header -->", replace="<!-- next-header -->\n## [Unreleased] - ReleaseDate\n", exactly=1},
  {file="CHANGELOG.md", search="<!-- next-url -->", replace="<!-- next-url -->\n[Unreleased]: https://github.com/epage/pytest-rs/compare/{{tag_name}}...HEAD", exactly=1},
]

[features]
default = ["color", "threads"]
color = ["libtest2-harness/color"]
threads = ["libtest2-harness/threads"]

[dependencies]
libtest2-harness = { version = "0.0.3", path = "../libtest2-harness" }

[dev-dependencies]
dunce = "1.0.4"
escargot = "0.5.8"
once_cell_polyfill = "1.56.0"
pathdiff = "0.2.1"
snapbox = { version = "0.6.0", features = ["json"] }

[lints]
workspace = true
